disabled = false
languageCode = "ja"
languageName = "日本語"
weight = 1
title = "電子電脳技術研究会"

[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006年1月2日"
  logo = "img/icon_Nobackground.png"
  # secondaryLogo = "img/logo.png"
  description = "筑波大学附属中学校電子電脳技術研究会 公式ホームページ"
  copyright = "©︎ { year } 電子電脳技術研究会"

[params.author]
   name = "電子電脳技術研究会"
#   email = "youremail@example.com"
   image = "img/icon_Nobackground.png"
   imageQuality = 96
   headline = "筑波大学附属中学校"
#   bio = ""
  links = [
    { twitter = "https://twitter.com/Tsukuba_Denden" },
#    { x-twitter = "https://twitter.com/Tsukuba_denden" },
    { youtube = "https://www.youtube.com/@Tsukuba-DenDen" },
    { github = "https://github.com/tsukuba-denden" },
#    { bluesky = "https://bsky.app/profile/??.bsky.social" },
  ]
