disabled = false
languageCode = "ja"
languageName = "日本語"
weight = 1
title = "〒«ゆうびんきょく»のホームページ"

[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006年1月2日"
  logo = "img/icon.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "〒«ゆうびんきょく»"
  copyright = "©︎ 2024 〒«ゆうびんきょく»"

[params.author]
   name = "〒«ゆうびんきょく»"
#   email = "youremail@example.com"
   image = "img/icon.png"
   imageQuality = 96
   headline = "ツイ廃マリカ勢ガジェオタプログラマー中学生"
#   bio = "ツイ廃マリカ勢ガジェオタプログラマー中学生"
  links = [

    { twitter = "https://twitter.com/yuubinnkyoku_mk" },
#    { x-twitter = "https://twitter.com/yuubinnkyoku" },
    { youtube = "https://youtube.com/@yuubinnkyoku" },
    { discord = "https://discord.gg/Ptabd9wgYR" },
    { github = "https://github.com/yuubinnkyoku" },
    { bluesky = "https://bsky.app/profile/yuubinnkyoku.bsky.social" },
    { instagram = "https://instagram.com/yuubinnkyoku_mk" },
#    { mastodon = "https://mstdn.jp/@yuubinnkyoku" },
    { reddit = "https://reddit.com/user/yuubinnkyoku" },
    { threads = "https://www.threads.net/@yuubinnkyoku_mk" },
    { tiktok = "https://tiktok.com/@yuubinnkyoku" },
    { twitch = "https://twitch.tv/yuubinnkyoku" },
    { link = "https://linktr.ee/yuubinnkyoku"},
  ]