# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "歴史"
  pageRef = "posts/history"
  weight = 20

[[main]]
  name = "活動内容"
  pageRef = "posts/活動内容"
  weight = 20

[[main]]
  name = "その他"
  weight = 30

[[main]]
  name = "tentative site"
  parent = "その他"
  url = "https://tsukuba-denden.github.io/tentative/"
  weight = 30

#[[main]]
#  name = "桐陰会雑誌"
#  parent = "その他"
#  pageRef = "posts/桐陰会雑誌"
#  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/tsukuba-denden"
  weight = 40

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/Tsukuba_Denden"
  weight = 41

  [[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://youtube.com/@Tsukuba_Denden"
  weight = 42

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
