# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Other"
  weight = 30

[[main]]
  name = "link to tags"
  parent = "Other"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "link to posts"
  parent = "Other"
  pageRef = "posts"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/yuubinnkyoku"
  weight = 40

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/yuubinnkyoku_mk"
  weight = 41

  [[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://youtube.com/@yuubinnkyoku"
  weight = 42

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
